"""deleted power column

Revision ID: 40cffc3710cb
Revises: c54917f1f3e0
Create Date: 2024-04-16 22:42:29.001746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '40cffc3710cb'
down_revision: Union[str, None] = 'c54917f1f3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'power')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('power', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
