"""change the Amount column

Revision ID: c9b625dc1e06
Revises: 40cffc3710cb
Create Date: 2024-04-17 04:06:50.052599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c9b625dc1e06'
down_revision: Union[str, None] = '40cffc3710cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waste', 'amount',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('organic_waste', 'plastic_waste', 'medical_waste', 'industrial_waste', name='amount'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waste', 'amount',
               existing_type=sa.Enum('organic_waste', 'plastic_waste', 'medical_waste', 'industrial_waste', name='amount'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
